### ISSUE TITLE
Windows 10 pro 32 bit does not work although says fully supported and listening.

### ISSUE THREAD

**Issue by BasitBulbulia** [SobieskiCodes/RDPWrap#2]
Can anyone assist me in getting my RDP to work multi-sessions - now its giving this error "The number of connections to this computer is limited and all connections . . . etc"

Version : 10.0.1.18362.267

**Comment by SobieskiCodes** [comment]
https://github.com/stascorp/rdpwrap/issues/906#issuecomment-548740923
Please use this ini for 32/x86
