### ISSUE TITLE
Support for Server2022？

### ISSUE THREAD

**Issue by onthehide288** [SobieskiCodes/RDPWrap#5]

**Comment by SobieskiCodes** [comment]
https://github.com/stascorp/rdpwrap/issues/2614

Support already exists with [sebaxakerhtc](https://github.com/sebaxakerhtc)'s auto generated [ini](https://github.com/sebaxakerhtc/rdpwrap.ini)
While the linked one might not be your exact version - you'll need to work within the ranges of the existing ones - this repo/tools purpose is to stop win10 updates and adjust privacy settings in adjacent to the work done by the original rdpwrap team, but now basically unofficially maintained by sebaxakerhtc (linked above).
