### ISSUE TITLE
10.0.26100.1

### ISSUE THREAD

**Issue by comcj** [SobieskiCodes/RDPWrap#6]
![1735517182533](https://github.com/user-attachments/assets/1b1b3e80-0c21-4946-bb83-64d9941cf366)

**Comment by comcj** [comment]
windows 11

**Comment by SobieskiCodes** [comment]
https://github.com/stascorp/rdpwrap/issues/3396
Use the [offset tool](https://github.com/llccd/RDPWrapOffsetFinder) to get the offsets you need and update your INI.
